"""Russian translations, keyed by the English source string."""

RU: dict[str, str] = {
    # stage 5: editing results
    "All statements run in one transaction. If one fails, nothing is written.": (
        "Все операторы выполняются в одной транзакции. Если один не пройдёт, не запишется ничего."
    ),
    "Applied {n} changes in {time}.": "Применено изменений: {n} за {time}.",
    "Apply": "Применить",
    "Apply &changes": "Применить &правки",
    "Apply changes…": "Применить правки…",
    "Apply them?": "Применить их?",
    "Change production data?": "Изменить данные в боевой базе?",
    "Choose key columns": "Выбор ключевых столбцов",
    "Choose key columns…": "Выбрать ключевые столбцы…",
    "Close it and discard them?": "Закрыть вкладку и отбросить их?",
    "Run it and discard them?": "Выполнить запрос и отбросить их?",
    "Copy": "Копировать",
    "Copy SQL": "Копировать SQL",
    "Copy as CSV": "Копировать как CSV",
    "Copy as Markdown": "Копировать как Markdown",
    "Copy with headers": "Копировать с заголовками",
    "Delete row": "Удалить строку",
    "Discard": "Отменить",
    "Discard changes": "Отменить правки",
    "Discard the changes?": "Отбросить правки?",
    "Duplicate row": "Дублировать строку",
    "Edit cell": "Править ячейку",
    "Edit in a dialog…": "Править в окне…",
    "Edit {name}": "Правка: {name}",
    "Editable · {table} (key: {key}) · F2 edit · Ctrl+N new row · Del delete": (
        "Можно править · {table} (ключ: {key}) · F2 правка · Ctrl+N новая строка · Del удалить"
    ),
    "Load the current rows; your changes are kept": "Загрузить текущие строки; ваши правки сохранятся",
    "New row": "Новая строка",
    "New row (Ctrl+N)": "Новая строка (Ctrl+N)",
    "Nothing was written.": "Ничего не записано.",
    "Pending changes: {n} · Alt+S apply · Esc discard": (
        "Ожидает подтверждения — изменений: {n} · Alt+S применить · Esc отменить"
    ),
    "Quit and discard them?": "Выйти и отбросить их?",
    "Quit without applying?": "Выйти, не применив правки?",
    "Read-only: only a plain SELECT from one table can be edited.": (
        "Только чтение: править можно только простой SELECT из одной таблицы."
    ),
    "Read-only: the columns do not match {name}.": "Только чтение: столбцы не соответствуют таблице {name}.",
    "Read-only: the database structure is not loaded yet.": (
        "Только чтение: структура базы данных ещё не загружена."
    ),
    "Read-only: the key columns ({columns}) are not in the result; add them to the SELECT list.": (
        "Только чтение: ключевых столбцов ({columns}) нет в результате; добавьте их в список SELECT."
    ),
    "Read-only: the structure of {name} is not known (yet).": (
        "Только чтение: структура {name} пока неизвестна."
    ),
    "Read-only: this connection is read-only.": "Только чтение: подключение открыто только для чтения.",
    "Read-only: this is not the rows of a single table (a join, grouping, DISTINCT, an aggregate or a subquery). Open the table to change its data.": (
        "Только чтение: это не строки одной таблицы (соединение, группировка, DISTINCT, агрегат "
        "или подзапрос). Откройте таблицу, чтобы изменить её данные."
    ),
    "Read-only: {name} has no primary key and no unique index.": (
        "Только чтение: у {name} нет первичного ключа и уникального индекса."
    ),
    "Read-only: {name} is a view.": "Только чтение: {name} — представление.",
    "Redo": "Повторить",
    "Redo (Ctrl+Y)": "Повторить (Ctrl+Y)",
    "Reload": "Перечитать",
    "Restore row": "Вернуть строку",
    "Revert this cell": "Вернуть ячейку",
    "Revert this row": "Вернуть строку как была",
    "Review the changes": "Проверьте правки",
    "Set NULL": "Записать NULL",
    "The change could not be written.": "Правку не удалось записать.",
    "The column {name} does not accept NULL.": "Столбец {name} не принимает NULL.",
    "The table {name} has no primary key. Tick the columns whose values are unique for every row: changes find their row by them. A change that would touch more than one row is refused and nothing is written.": (
        "У таблицы {name} нет первичного ключа. Отметьте столбцы, значения которых уникальны для "
        "каждой строки: по ним правки находят свою строку. Правка, затрагивающая больше одной "
        "строки, отклоняется, и ничего не записывается."
    ),
    "There are {n} changes in the grids that were not applied.": (
        "В таблицах есть неприменённые правки: {n}."
    ),
    "This is the PRODUCTION connection “{name}”. {n} statements will change its data.": (
        "Это БОЕВОЕ подключение «{name}». Операторов, меняющих данные: {n}."
    ),
    "This row will be deleted.": "Эта строка будет удалена.",
    "This row will be inserted.": "Эта строка будет добавлена.",
    "This tab has {n} changes that were not applied.": "На этой вкладке неприменённых правок: {n}.",
    "Undo": "Отменить действие",
    "Undo (Ctrl+Z)": "Отменить действие (Ctrl+Z)",
    "Use the default": "Значение по умолчанию",
    "a UUID": "UUID",
    "a date (YYYY-MM-DD)": "дата (ГГГГ-ММ-ДД)",
    "a date and time (YYYY-MM-DD HH:MM:SS)": "дата и время (ГГГГ-ММ-ДД ЧЧ:ММ:СС)",
    "a number": "число",
    "a time (HH:MM:SS)": "время (ЧЧ:ММ:СС)",
    "a valid value": "допустимое значение",
    "a whole number": "целое число",
    "default": "по умолчанию",
    "false": "ложь",
    "rows to add: {n}": "добавить строк: {n}",
    "rows to change: {n}": "изменить строк: {n}",
    "rows to delete: {n}": "удалить строк: {n}",
    "true": "истина",
    "true or false": "истина или ложь",
    "valid JSON": "корректный JSON",
    "was: {value}": "было: {value}",
    "{name}: expected {what}.": "{name}: ожидается {what}.",
    "{row}the key matches {n} rows, so the change was refused. Nothing was written. Choose key columns that are unique.": (
        "{row}ключу соответствует строк: {n}, поэтому правка отклонена. Ничего не записано. "
        "Выберите уникальные ключевые столбцы."
    ),
    "{row}was changed or deleted by someone else since it was loaded. Nothing was written. Reload to see the current rows; your changes are kept.": (
        "{row}кто-то другой изменил или удалил эту строку после загрузки. Ничего не записано. "
        "Перечитайте строки, чтобы увидеть текущие данные; ваши правки сохранятся."
    ),
    # stage 4: autocomplete
    "&Autocomplete": "&Автодополнение",
    "Keyword case": "Регистр ключевых слов",
    "UPPER CASE (SELECT)": "ВЕРХНИЙ РЕГИСТР (SELECT)",
    "lower case (select)": "нижний регистр (select)",
    "As typed": "Как набрано",
    "{n} cols": "столбцов: {n}",
    "{n} columns": "столбцов: {n}",
    "{n} columns: {names}": "столбцов: {n} — {names}",
    "common table expression of this statement": "общее табличное выражение (CTE) этого запроса",
    "schema": "схема",
    "output column": "столбец результата",
    "subquery": "подзапрос",
    "alias of {name}": "псевдоним для {name}",
    "table {name}": "таблица {name}",
    "type": "тип",
    "in {name}": "из {name}",
    "foreign key {table}({columns})": "внешний ключ {table}({columns})",
    "foreign key {table}({columns}) → {ref}({ref_columns})": (
        "внешний ключ {table}({columns}) → {ref}({ref_columns})"
    ),
    "Replace * with the list of columns": "Заменить * списком столбцов",
    "aggregate function": "агрегатная функция",
    "window function": "оконная функция",
    "string function": "строковая функция",
    "numeric function": "числовая функция",
    "date and time function": "функция даты и времени",
    "conditional expression": "условное выражение",
    "JSON function": "функция JSON",
    "array function": "функция для массивов",
    "system function": "системная функция",
    "function": "функция",
    "all columns of a table": "все столбцы таблицы",
    "count the rows": "посчитать строки",
    "distinct values": "уникальные значения",
    "insert a row": "добавить строку",
    "change rows": "изменить строки",
    "delete rows": "удалить строки",
    "common table expression": "общее табличное выражение",
    "rows with a match": "строки, у которых есть пара",
    "keep every left row": "оставить все строки слева",
    "keep every right row": "оставить все строки справа",
    "every combination": "все сочетания строк",
    "sort the rows": "отсортировать строки",
    "group the rows": "сгруппировать строки",
    "first 100 rows": "первые 100 строк",
    # stage 3: schema, diagram, table tabs
    "&Database": "&База данных",
    "&Fit diagram": "&Вписать диаграмму",
    "&Go to table…": "Перейти к &таблице…",
    "&Refresh structure": "&Обновить структуру",
    "&Reset diagram layout": "&Сбросить расположение диаграммы",
    "Show the &diagram": "Показывать &диаграмму",
    "Show the diagram": "Показать диаграмму",
    "Hide the diagram": "Скрыть диаграмму",
    "+ {n} more columns": "+ ещё столбцов: {n}",
    "show fewer columns": "свернуть столбцы",
    "All schemas": "Все схемы",
    "Schema shown in the diagram": "Схема на диаграмме",
    "Search tables and columns…": "Поиск таблиц и столбцов…",
    "Re-read the database structure": "Заново прочитать структуру базы",
    "Reset the card layout": "Сбросить расположение карточек",
    "Controls": "Управление",
    "Zoom in (Ctrl++)": "Приблизить (Ctrl++)",
    "Zoom out (Ctrl+-)": "Отдалить (Ctrl+-)",
    "Fit everything (Ctrl+0)": "Вписать всё (Ctrl+0)",
    "fit everything": "вписать всё",
    "zoom": "масштаб",
    "Mouse wheel — zoom": "Колесо мыши — масштаб",
    "Drag the background — move around": "Перетаскивание фона — прокрутка",
    "Drag a card — rearrange (remembered)": "Перетаскивание карточки — расположение (запоминается)",
    "Click a column — insert its name in the editor": "Клик по столбцу — вставить его имя в редактор",
    "Double-click a card — open the table's data": "Двойной клик по карточке — открыть данные таблицы",
    "Right-click a card — more actions": "Правый клик по карточке — другие действия",
    "Select a card — highlight related tables": "Выбрать карточку — подсветить связанные таблицы",
    "Open data": "Открыть данные",
    "SELECT * FROM this table": "SELECT * FROM эта таблица",
    "Insert table name": "Вставить имя таблицы",
    "Copy table name": "Копировать имя таблицы",
    "Could not read the database structure": "Не удалось прочитать структуру базы данных",
    "Reading the database structure…": "Читаем структуру базы данных…",
    "The database structure has not been read yet.": "Структура базы данных ещё не прочитана.",
    "The database structure is not loaded yet.": "Структура базы данных ещё не загружена.",
    "This database has no tables yet.": "В этой базе данных пока нет таблиц.",
    "Create one in the editor and press refresh.": "Создайте таблицу в редакторе и нажмите «обновить».",
    "Try again": "Повторить",
    "{tables} tables · {relations} relations": "таблиц: {tables} · связей: {relations}",
    "read in {ms} ms": "прочитано за {ms} мс",
    "Go to table or column": "Переход к таблице или столбцу",
    "Type a table or column name…": "Введите имя таблицы или столбца…",
    "view": "вид",
    "matview": "матпредст.",
    "columns": "столбцов",
    "about {n} rows": "примерно строк: {n}",
    "primary key": "первичный ключ",
    "NOT NULL": "NOT NULL (не пусто)",
    "default {value}": "по умолчанию {value}",
    "optional": "необязательная",
    "required": "обязательная",
    "Reload this page": "Перечитать страницу",
    "Previous page": "Предыдущая страница",
    "Next page": "Следующая страница",
    "WHERE condition, e.g. id > 10 AND name LIKE 'a%'": "Условие WHERE, например id > 10 AND name LIKE 'a%'",
    "Loading…": "Загрузка…",
    "Could not load the rows": "Не удалось загрузить строки",
    "No rows match the filter.": "Нет строк, подходящих под фильтр.",
    "This table is empty.": "Таблица пуста.",
    "rows {first}-{last}": "строки {first}-{last}",
    "junction table: links the tables it references (many-to-many)": "связующая таблица: соединяет таблицы, на которые ссылается (многие ко многим)",
    "about {n} in the table": "всего примерно {n}",
    # connection dialog
    "Connections": "Подключения",
    "Saved connections": "Сохранённые подключения",
    "+ New": "+ Новое",
    "Duplicate": "Дублировать",
    "Delete": "Удалить",
    "Test": "Проверить",
    "Save": "Сохранить",
    "Connect": "Подключиться",
    "Close": "Закрыть",
    "Unsaved changes": "Несохранённые изменения",
    "The connection has unsaved changes. Save them?": "В подключении есть несохранённые изменения. Сохранить их?",
    "Delete connection": "Удаление подключения",
    "Delete the connection “{name}”? Its saved password is removed too.": "Удалить подключение «{name}»? Сохранённый пароль тоже будет удалён.",
    "Connection works.": "Подключение работает.",
    "Saved.": "Сохранено.",
    "No group": "Без группы",
    "The password was not saved: the password store is locked.": "Пароль не сохранён: хранилище паролей заблокировано.",
    "Testing the connection…": "Проверяем подключение…",
    # test steps
    "DNS lookup": "Поиск адреса (DNS)",
    "Port reachable": "Порт доступен",
    "Sign in": "Вход",
    "Test query": "Тестовый запрос",
    "Database file": "Файл базы данных",
    "Open file": "Открытие файла",
    # form
    "My database": "Моя база данных",
    "No colour": "Без цвета",
    "URL": "URL",
    "Host / Port": "Хост / порт",
    "File": "Файл",
    "Password": "Пароль",
    "Save the password in the {store}": "Сохранить пароль в хранилище ({store})",
    "password store": "хранилище паролей",
    "Read-only": "Только чтение",
    "Production database": "Рабочая (production) база",
    "Connection URL": "URL подключения",
    "Paste a URL and the fields update. The password is kept separately.": "Вставьте URL, и поля обновятся. Пароль хранится отдельно.",
    "Open…": "Открыть…",
    "New…": "Создать…",
    "Create the file if it does not exist": "Создать файл, если его нет",
    "Open database file": "Открыть файл базы данных",
    "SQLite databases (*.db *.sqlite *.sqlite3 *.db3);;All files (*)": "Базы SQLite (*.db *.sqlite *.sqlite3 *.db3);;Все файлы (*)",
    "New database file": "Новый файл базы данных",
    "Host": "Хост",
    "Port": "Порт",
    "User": "Пользователь",
    "Database": "База данных",
    "Extra parameters": "Дополнительные параметры",
    "Give the connection a name.": "Укажите название подключения.",
    "default ({port})": "по умолчанию ({port})",
    "Name": "Название",
    "Colour": "Цвет",
    "Group": "Группа",
    "A saved password is used. Type to replace it.": "Используется сохранённый пароль. Введите новый, чтобы заменить.",
    "Choose the database file.": "Выберите файл базы данных.",
    "Red": "Красный",
    "Orange": "Оранжевый",
    "Yellow": "Жёлтый",
    "Green": "Зелёный",
    "Teal": "Бирюзовый",
    "Blue": "Синий",
    "Purple": "Фиолетовый",
    "Gray": "Серый",
    # db switcher
    "Manage connections…": "Управление подключениями…",
    "Choose the database to work with": "Выберите базу данных для работы",
    "Connected": "Подключено",
    "Connecting…": "Подключение…",
    "Connection failed": "Не удалось подключиться",
    "Not connected": "Нет подключения",
    "No saved connections": "Нет сохранённых подключений",
    "Select a connection": "Выберите подключение",
    # failure hints
    "Check the host name, your network connection and VPN.": "Проверьте имя хоста, сетевое подключение и VPN.",
    "The host is reachable but nothing accepts connections on this port. Check that the server is running and that the port is correct.": "Хост доступен, но на этом порту никто не принимает подключения. Проверьте, что сервер запущен и порт указан верно.",
    "The server did not answer in time. A firewall may be dropping the connection.": "Сервер не ответил вовремя. Возможно, подключение блокирует файрвол.",
    "Check the user name and the password.": "Проверьте имя пользователя и пароль.",
    "The server is reachable, but it has no database with this name.": "Сервер доступен, но базы данных с таким именем на нём нет.",
    "Check the path of the database file.": "Проверьте путь к файлу базы данных.",
    "Check the extra parameters of the connection.": "Проверьте дополнительные параметры подключения.",
    "Set the missing environment variables and try again.": "Задайте недостающие переменные окружения и повторите попытку.",
    "The saved password could not be read. Unlock the password store first.": "Не удалось прочитать сохранённый пароль. Сначала разблокируйте хранилище паролей.",
    # main window
    "&File": "&Файл",
    "&Connections…": "&Подключения…",
    "&Quit": "&Выход",
    "&View": "&Вид",
    "Language": "Язык",
    "Connections…": "Подключения…",
    "The database diagram will appear here.": "Здесь появится диаграмма базы данных.",
    "The language changes the next time the application starts.": "Язык изменится при следующем запуске приложения.",
    "Dark theme": "Тёмная тема",
    "Light theme": "Светлая тема",
    "System default": "Как в системе",
    "No connection": "Нет подключения",
    "Connected to {name}": "Подключено: {name}",
    "Connecting to {name}…": "Подключение к {name}…",
    "Could not connect to {name}": "Не удалось подключиться к {name}",
    "{name} is not connected": "{name}: нет подключения",
    "The password store stayed locked.": "Хранилище паролей осталось заблокированным.",
    "Password required": "Нужен пароль",
    "Password for {name}:": "Пароль для {name}:",
    "A configuration file was damaged": "Файл конфигурации повреждён",
    "A configuration file could not be read. It was kept as:\n{path}\nValid entries were restored.": "Файл конфигурации не удалось прочитать. Он сохранён как:\n{path}\nКорректные записи восстановлены.",
    "PRODUCTION": "PRODUCTION",
    "system keyring": "системное хранилище",
    "encrypted vault": "зашифрованное хранилище",
    "memory (until the app is closed)": "память, до закрытия приложения",
    # master password
    "No system keyring was found, so passwords are kept in an encrypted file protected by a master password.\n\nChoose a master password:": "Системное хранилище паролей не найдено, поэтому пароли хранятся в зашифрованном файле, защищённом мастер-паролем.\n\nПридумайте мастер-пароль:",
    "Master password for the saved passwords:": "Мастер-пароль для сохранённых паролей:",
    "Create master password": "Создание мастер-пароля",
    "Repeat the master password:": "Повторите мастер-пароль:",
    "Unlock saved passwords": "Разблокировка сохранённых паролей",
    "Wrong master password.": "Неверный мастер-пароль.",
    "The passwords do not match.": "Пароли не совпадают.",
    "Wrong master password. Try again:": "Неверный мастер-пароль. Попробуйте ещё раз:",
    # session panel
    "Cancel": "Отмена",
    "Retry": "Повторить",
    "Edit connection…": "Изменить подключение…",
    "Disconnect": "Отключиться",
    "No connection selected": "Подключение не выбрано",
    "Pick a database in the list on the right, or create a connection.": "Выберите базу в списке справа или создайте подключение.",
    "Read and write": "Чтение и запись",
    "Database system": "СУБД",
    "Address": "Адрес",
    "Mode": "Режим",
    # stage 2: editor, results, query menu
    "&Query": "&Запрос",
    "&Run": "&Выполнить",
    "Run &script": "Выполнить &скрипт",
    "S&top": "&Остановить",
    "&Format": "&Форматировать",
    "&New tab": "&Новая вкладка",
    "&Close tab": "&Закрыть вкладку",
    "Row limit": "Лимит строк",
    "Run": "Выполнить",
    "Run script": "Выполнить скрипт",
    "Stop": "Стоп",
    "Format": "Формат",
    "New query tab (Ctrl+T)": "Новая вкладка запроса (Ctrl+T)",
    "Run the selection or the current statement (Ctrl+Enter)": "Выполнить выделенное или текущий оператор (Ctrl+Enter)",
    "Run every statement in order (F5)": "Выполнить все операторы по порядку (F5)",
    "Cancel the running query (Esc)": "Отменить выполняемый запрос (Esc)",
    "Format the SQL (Ctrl+Shift+F)": "Отформатировать SQL (Ctrl+Shift+F)",
    "SQL dialect of this tab": "Диалект SQL этой вкладки",
    "Query {n}": "Запрос {n}",
    "Rename tab": "Переименование вкладки",
    "Tab name:": "Название вкладки:",
    "Cancelling…": "Отмена…",
    "The connection is not ready.": "Подключение не готово.",
    "There is nothing to run.": "Нечего выполнять.",
    "drops {target}": "удаляет {target}",
    "empties {target}": "полностью очищает {target}",
    "deletes every row of {target}": "удаляет все строки в {target}",
    "changes every row of {target}": "меняет все строки в {target}",
    "an object": "объект",
    "it changes data on the PRODUCTION connection “{name}”": "меняет данные на PRODUCTION-подключении «{name}»",
    "Run this?": "Выполнить?",
    "This script:": "Этот скрипт:",
    "Run it anyway?": "Всё равно выполнить?",
    "Failed after {time}": "Ошибка через {time}",
    "Cancelled after {time}": "Отменено через {time}",
    "Done in {time}": "Выполнено за {time}",
    "Running… {time}": "Выполняется… {time}",
    "line": "строка",
    "column": "столбец",
    "Formatted.": "Отформатировано.",
    "Filter rows…": "Фильтр строк…",
    "Your query returned no data": "Ваш запрос не вернул никаких данных",
    "{count} rows": "Строк: {count}",
    "{shown} of {total} rows": "Строк: {shown} из {total}",
    "cut off at {limit} rows": "обрезано на {limit} строках",
    "Run a query to see results here.": "Выполните запрос, и результаты появятся здесь.",
    "Result {n}": "Результат {n}",
    "Query OK": "Запрос выполнен",
    "{count} rows affected": "Затронуто строк: {count}",
    "OK {n}": "Готово {n}",
    "Query failed": "Ошибка запроса",
    "Error {n}": "Ошибка {n}",
    "Cancelled": "Отменено",
    "The statement was stopped.": "Выполнение оператора остановлено.",
    "Cancelled {n}": "Отмена {n}",
    "Skipped": "Пропущено",
    "An earlier statement failed or was cancelled.": "Предыдущий оператор завершился ошибкой или был отменён.",
    "Skipped {n}": "Пропуск {n}",
    # stage 6: TLS, SSH tunnel, pgpass / pg_service.conf
    "A saved passphrase is used. Type to replace it.": "Используется сохранённая фраза. Введите новую, чтобы заменить.",
    "A saved secret is used. Type to replace it.": "Используется сохранённый секрет. Введите новый, чтобы заменить.",
    "All files (*)": "Все файлы (*)",
    "Always encrypted, but the server's identity is not checked.": "Всегда шифруется, но личность сервера не проверяется.",
    "Browse…": "Обзор…",
    "CA certificate": "Сертификат CA",
    "Check the SSH host name and port, your network connection and VPN.": "Проверьте имя и порт SSH-сервера, сеть и VPN.",
    "Check the SSH private key file and its passphrase.": "Проверьте файл закрытого SSH-ключа и его парольную фразу.",
    "Choose a file": "Выберите файл",
    "Client certificate": "Клиентский сертификат",
    "Client key": "Клиентский ключ",
    "Connect through an SSH tunnel": "Подключаться через SSH-туннель",
    "Define the service in ~/.pg_service.conf or choose another one.": "Опишите сервис в ~/.pg_service.conf или выберите другой.",
    "Driver default": "По умолчанию (драйвер)",
    "Encrypted; the certificate must be signed by the CA below (or a system CA).": "Шифруется; сертификат должен быть подписан указанным ниже CA (или системным).",
    "Encryption": "Шифрование",
    "Enter the SSH server host name.": "Укажите адрес SSH-сервера.",
    "Enter the host name (or a service).": "Укажите адрес сервера (или сервис).",
    "Enter the jump host name.": "Укажите адрес промежуточного узла.",
    "Fix the certificate or key file named above in the SSL / TLS tab.": "Исправьте файл сертификата или ключа, названный выше, на вкладке SSL / TLS.",
    "Jump host": "Промежуточный узел",
    "Jump host password for {name}:": "Пароль промежуточного узла для {name}:",
    "Key passphrase": "Парольная фраза ключа",
    "Key passphrase (if the key has one)": "Парольная фраза ключа (если она есть)",
    "Like verify-ca, and the certificate must be issued for the host name.": "Как verify-ca, и сертификат должен быть выдан именно на это имя сервера.",
    "No encryption at all.": "Без шифрования.",
    "PEM files (*.pem *.crt *.cer *.key);;All files (*)": "Файлы PEM (*.pem *.crt *.cer *.key);;Все файлы (*)",
    "Passphrase of the SSH key for {name}:": "Парольная фраза SSH-ключа для {name}:",
    "Passphrase of the TLS client key for {name}:": "Парольная фраза клиентского TLS-ключа для {name}:",
    "Passphrase of the jump host key for {name}:": "Парольная фраза ключа промежуточного узла для {name}:",
    "Password source": "Источник пароля",
    "Plain first; TLS only if the server insists (PostgreSQL).": "Сначала без шифрования; TLS, только если сервер настоит (PostgreSQL).",
    "Private key": "Закрытый ключ",
    "Private key file": "Файл закрытого ключа",
    "Reach the SSH server through a jump host (bastion)": "Добираться до SSH-сервера через промежуточный узел (бастион)",
    "SSH jump host": "SSH: промежуточный узел",
    "SSH login": "SSH: вход",
    "SSH password for {name}:": "SSH-пароль для {name}:",
    "SSH passwords and key passphrases are kept the same way.": "SSH-пароли и парольные фразы ключей хранятся так же.",
    "SSH server": "SSH-сервер",
    "SSH tunnel": "SSH-туннель",
    "SSL / TLS": "SSL / TLS",
    "Secret for {name}:": "Секрет для {name}:",
    "Service": "Сервис",
    "Service file": "Файл сервисов",
    "Settings": "Настройки",
    "Sign in with": "Способ входа",
    "TLS files": "Файлы TLS",
    "TLS negotiation failed. Check the mode and the certificates in the SSL / TLS tab.": "Не удалось согласовать TLS. Проверьте режим и сертификаты на вкладке SSL / TLS.",
    "TLS when the server offers it, otherwise plain.": "TLS, если сервер его предлагает, иначе без шифрования.",
    "The SSH login worked, but the SSH server cannot reach the database host and port. Check them from the SSH server's point of view.": "Вход по SSH удался, но SSH-сервер не может достучаться до базы по этому адресу и порту. Проверьте их с точки зрения SSH-сервера.",
    "The SSH server refused the login. Check the user, the password or the key.": "SSH-сервер отклонил вход. Проверьте пользователя, пароль или ключ.",
    "The SSH server's key is not the one you trusted. If nobody reinstalled the server, do not connect: somebody may be intercepting the connection.": "Ключ SSH-сервера не тот, которому вы доверяли. Если сервер никто не переустанавливал, не подключайтесь: соединение могут перехватывать.",
    "The driver decides: PostgreSQL tries TLS first, MySQL uses it when offered.": "Решает драйвер: PostgreSQL сначала пробует TLS, MySQL использует его, если сервер предлагает.",
    "The identity of {host}:{port} is not known yet.\n\n{key_type} key fingerprint:\n{fingerprint}\n\nCompare it with the one your administrator gave you. Trust this server?": (
        "Личность {host}:{port} пока неизвестна.\n\nОтпечаток ключа {key_type}:\n{fingerprint}\n\nСверьте его с тем, что дал администратор. Доверять этому серверу?"
    ),
    "This SSH server has not been seen before. Compare its fingerprint with the administrator's, then trust it.": "Этот SSH-сервер раньше не встречался. Сверьте его отпечаток с отпечатком от администратора и только потом доверьтесь.",
    "Trust this SSH server?": "Доверять этому SSH-серверу?",
    "Trust this server…": "Доверять этому серверу…",
    "Type the SSH password or key passphrase (SSH tunnel tab) and try again.": "Введите SSH-пароль или парольную фразу ключа (вкладка «SSH-туннель») и повторите.",
    "optional — a service from pg_service.conf": "необязательно — сервис из pg_service.conf",
    "ssh-agent": "ssh-agent",
    "{file} has a password for this connection (line {line}); it is used when none is saved.": "В {file} есть пароль для этого подключения (строка {line}); он используется, если сохранённого нет.",
    "{file} has no line for this connection.": "В {file} нет строки для этого подключения.",
}
