"""Ukrainian translations, keyed by the English source string."""

UK: dict[str, str] = {
    "All statements run in one transaction. If one fails, nothing is written.": "Усі оператори виконуються в одній транзакції. Якщо один завершиться помилкою, нічого не буде записано.",
    "Applied {n} changes in {time}.": "Застосовано змін: {n} за {time}.",
    "Apply": "Застосувати",
    "Apply &changes": "Застосувати &зміни",
    "Apply changes…": "Застосувати зміни…",
    "Apply them?": "Застосувати їх?",
    "Change production data?": "Змінити дані в робочій базі?",
    "Choose key columns": "Вибір ключових стовпців",
    "Choose key columns…": "Вибрати ключові стовпці…",
    "Close it and discard them?": "Закрити вкладку та відхилити зміни?",
    "Run it and discard them?": "Виконати запит і відхилити зміни?",
    "Copy": "Копіювати",
    "Copy SQL": "Копіювати SQL",
    "Copy as CSV": "Копіювати як CSV",
    "Copy as Markdown": "Копіювати як Markdown",
    "Copy with headers": "Копіювати із заголовками",
    "Delete row": "Видалити рядок",
    "Discard": "Відхилити",
    "Discard changes": "Відхилити зміни",
    "Discard the changes?": "Відхилити зміни?",
    "Duplicate row": "Дублювати рядок",
    "Edit cell": "Редагувати комірку",
    "Edit in a dialog…": "Редагувати у вікні…",
    "Edit {name}": "Редагування: {name}",
    "Editable · {table} (key: {key}) · F2 edit · Ctrl+N new row · Del delete": "Можна редагувати · {table} (ключ: {key}) · F2 редагувати · Ctrl+N новий рядок · Del видалити",
    "Load the current rows; your changes are kept": "Завантажити поточні рядки; ваші зміни збережуться",
    "New row": "Новий рядок",
    "New row (Ctrl+N)": "Новий рядок (Ctrl+N)",
    "Nothing was written.": "Нічого не записано.",
    "Pending changes: {n} · Alt+S apply · Esc discard": "Очікують застосування — змін: {n} · Alt+S застосувати · Esc відхилити",
    "Quit and discard them?": "Вийти та відхилити зміни?",
    "Quit without applying?": "Вийти без застосування змін?",
    "Read-only: only a plain SELECT from one table can be edited.": "Лише читання: редагувати можна тільки простий SELECT з однієї таблиці.",
    "Read-only: the columns do not match {name}.": "Лише читання: стовпці не відповідають таблиці {name}.",
    "Read-only: the database structure is not loaded yet.": "Лише читання: структуру бази даних ще не завантажено.",
    "Read-only: the key columns ({columns}) are not in the result; add them to the SELECT list.": "Лише читання: ключових стовпців ({columns}) немає в результаті; додайте їх до списку SELECT.",
    "Read-only: the structure of {name} is not known (yet).": "Лише читання: структура {name} поки невідома.",
    "Read-only: this connection is read-only.": "Лише читання: це підключення відкрито лише для читання.",
    "Read-only: this is not the rows of a single table (a join, grouping, DISTINCT, an aggregate or a subquery). Open the table to change its data.": "Лише читання: це не рядки однієї таблиці (з'єднання, групування, DISTINCT, агрегат або підзапит). Відкрийте таблицю, щоб змінити її дані.",
    "Read-only: {name} has no primary key and no unique index.": "Лише читання: у {name} немає первинного ключа й унікального індексу.",
    "Read-only: {name} is a view.": "Лише читання: {name} — представлення.",
    "Redo": "Повторити",
    "Redo (Ctrl+Y)": "Повторити (Ctrl+Y)",
    "Reload": "Оновити",
    "Restore row": "Відновити рядок",
    "Revert this cell": "Повернути комірку",
    "Revert this row": "Повернути рядок як було",
    "Review the changes": "Перевірте зміни",
    "Set NULL": "Записати NULL",
    "The change could not be written.": "Не вдалося записати зміну.",
    "The column {name} does not accept NULL.": "Стовпець {name} не приймає NULL.",
    "The table {name} has no primary key. Tick the columns whose values are unique for every row: changes find their row by them. A change that would touch more than one row is refused and nothing is written.": "У таблиці {name} немає первинного ключа. Позначте стовпці, значення яких унікальні для кожного рядка: за ними зміни знаходять свій рядок. Зміна, що торкається більше ніж одного рядка, відхиляється, і нічого не записується.",
    "There are {n} changes in the grids that were not applied.": "У сітках є незастосовані зміни: {n}.",
    "This is the PRODUCTION connection “{name}”. {n} statements will change its data.": "Це РОБОЧЕ (PRODUCTION) підключення «{name}». Операторів, що змінюють його дані: {n}.",
    "This row will be deleted.": "Цей рядок буде видалено.",
    "This row will be inserted.": "Цей рядок буде додано.",
    "This tab has {n} changes that were not applied.": "На цій вкладці є незастосовані зміни: {n}.",
    "Undo": "Скасувати",
    "Undo (Ctrl+Z)": "Скасувати (Ctrl+Z)",
    "Use the default": "Використати значення за замовчуванням",
    "a UUID": "UUID",
    "a date (YYYY-MM-DD)": "дата (РРРР-ММ-ДД)",
    "a date and time (YYYY-MM-DD HH:MM:SS)": "дата й час (РРРР-ММ-ДД ГГ:ХХ:СС)",
    "a number": "число",
    "a time (HH:MM:SS)": "час (ГГ:ХХ:СС)",
    "a valid value": "допустиме значення",
    "a whole number": "ціле число",
    "default": "типово",
    "false": "хибність",
    "rows to add: {n}": "рядків для додавання: {n}",
    "rows to change: {n}": "рядків для зміни: {n}",
    "rows to delete: {n}": "рядків для видалення: {n}",
    "true": "істина",
    "true or false": "істина або хибність",
    "valid JSON": "коректний JSON",
    "was: {value}": "було: {value}",
    "{name}: expected {what}.": "{name}: очікується {what}.",
    "{row}the key matches {n} rows, so the change was refused. Nothing was written. Choose key columns that are unique.": "{row}ключу відповідає рядків: {n}, тому зміну відхилено. Нічого не записано. Виберіть унікальні ключові стовпці.",
    "{row}was changed or deleted by someone else since it was loaded. Nothing was written. Reload to see the current rows; your changes are kept.": "{row}хтось інший змінив або видалив цей рядок після завантаження. Нічого не записано. Оновіть, щоб побачити поточні рядки; ваші зміни збережуться.",
    "&Autocomplete": "&Автодоповнення",
    "Keyword case": "Регістр ключових слів",
    "UPPER CASE (SELECT)": "ВЕРХНІЙ РЕГІСТР (SELECT)",
    "lower case (select)": "нижній регістр (select)",
    "As typed": "Як введено",
    "{n} cols": "стовпців: {n}",
    "{n} columns": "стовпців: {n}",
    "{n} columns: {names}": "стовпців: {n} — {names}",
    "common table expression of this statement": "загальний табличний вираз (CTE) цього оператора",
    "schema": "схема",
    "output column": "стовпець результату",
    "subquery": "підзапит",
    "alias of {name}": "псевдонім для {name}",
    "table {name}": "таблиця {name}",
    "type": "тип",
    "in {name}": "у {name}",
    "foreign key {table}({columns})": "зовнішній ключ {table}({columns})",
    "foreign key {table}({columns}) → {ref}({ref_columns})": "зовнішній ключ {table}({columns}) → {ref}({ref_columns})",
    "Replace * with the list of columns": "Замінити * списком стовпців",
    "aggregate function": "агрегатна функція",
    "window function": "віконна функція",
    "string function": "рядкова функція",
    "numeric function": "числова функція",
    "date and time function": "функція дати й часу",
    "conditional expression": "умовний вираз",
    "JSON function": "функція JSON",
    "array function": "функція для масивів",
    "system function": "системна функція",
    "function": "функція",
    "all columns of a table": "усі стовпці таблиці",
    "count the rows": "порахувати рядки",
    "distinct values": "унікальні значення",
    "insert a row": "додати рядок",
    "change rows": "змінити рядки",
    "delete rows": "видалити рядки",
    "common table expression": "загальний табличний вираз",
    "rows with a match": "рядки, що мають відповідник",
    "keep every left row": "залишити всі рядки зліва",
    "keep every right row": "залишити всі рядки справа",
    "every combination": "усі комбінації рядків",
    "sort the rows": "відсортувати рядки",
    "group the rows": "згрупувати рядки",
    "first 100 rows": "перші 100 рядків",
    "&Database": "&База даних",
    "&Fit diagram": "&Вписати діаграму",
    "&Go to table…": "Перейти до &таблиці…",
    "&Refresh structure": "&Оновити структуру",
    "&Reset diagram layout": "&Скинути розташування діаграми",
    "Show the &diagram": "Показувати &діаграму",
    "Show the diagram": "Показати діаграму",
    "Hide the diagram": "Приховати діаграму",
    "+ {n} more columns": "+ ще стовпців: {n}",
    "show fewer columns": "згорнути стовпці",
    "All schemas": "Усі схеми",
    "Schema shown in the diagram": "Схема на діаграмі",
    "Search tables and columns…": "Пошук таблиць і стовпців…",
    "Re-read the database structure": "Перечитати структуру бази даних",
    "Reset the card layout": "Скинути розташування карток",
    "Controls": "Керування",
    "Zoom in (Ctrl++)": "Збільшити (Ctrl++)",
    "Zoom out (Ctrl+-)": "Зменшити (Ctrl+-)",
    "Fit everything (Ctrl+0)": "Вмістити все (Ctrl+0)",
    "fit everything": "вмістити все",
    "zoom": "масштаб",
    "Mouse wheel — zoom": "Коліщатко миші — масштаб",
    "Drag the background — move around": "Перетягування тла — прокручування",
    "Drag a card — rearrange (remembered)": "Перетягування картки — зміна розташування (запам'ятовується)",
    "Click a column — insert its name in the editor": "Клік по стовпцю — вставити його назву в редактор",
    "Double-click a card — open the table's data": "Подвійний клік по картці — відкрити дані таблиці",
    "Right-click a card — more actions": "Клік правою кнопкою по картці — інші дії",
    "Select a card — highlight related tables": "Вибір картки — підсвітити пов'язані таблиці",
    "Open data": "Відкрити дані",
    "SELECT * FROM this table": "SELECT * FROM ця таблиця",
    "Insert table name": "Вставити назву таблиці",
    "Copy table name": "Копіювати назву таблиці",
    "Could not read the database structure": "Не вдалося прочитати структуру бази даних",
    "Reading the database structure…": "Читання структури бази даних…",
    "The database structure has not been read yet.": "Структуру бази даних ще не прочитано.",
    "The database structure is not loaded yet.": "Структуру бази даних ще не завантажено.",
    "This database has no tables yet.": "У цій базі даних поки немає таблиць.",
    "Create one in the editor and press refresh.": "Створіть таблицю в редакторі та натисніть «оновити».",
    "Try again": "Повторити",
    "{tables} tables · {relations} relations": "таблиць: {tables} · зв'язків: {relations}",
    "read in {ms} ms": "прочитано за {ms} мс",
    "Go to table or column": "Перехід до таблиці або стовпця",
    "Type a table or column name…": "Введіть назву таблиці або стовпця…",
    "view": "подання",
    "matview": "мат. подання",
    "columns": "стовпців",
    "about {n} rows": "приблизно рядків: {n}",
    "primary key": "первинний ключ",
    "NOT NULL": "NOT NULL (не порожньо)",
    "default {value}": "типово {value}",
    "optional": "необов'язково",
    "required": "обов'язково",
    "Reload this page": "Оновити цю сторінку",
    "Previous page": "Попередня сторінка",
    "Next page": "Наступна сторінка",
    "WHERE condition, e.g. id > 10 AND name LIKE 'a%'": "Умова WHERE, наприклад id > 10 AND name LIKE 'a%'",
    "Loading…": "Завантаження…",
    "Could not load the rows": "Не вдалося завантажити рядки",
    "No rows match the filter.": "Немає рядків, що відповідають фільтру.",
    "This table is empty.": "Таблиця порожня.",
    "rows {first}-{last}": "рядки {first}-{last}",
    "junction table: links the tables it references (many-to-many)": "сполучна таблиця: з'єднує таблиці, на які посилається (багато до багатьох)",
    "about {n} in the table": "усього приблизно {n}",
    "Connections": "Підключення",
    "Saved connections": "Збережені підключення",
    "+ New": "+ Нове",
    "Duplicate": "Дублювати",
    "Delete": "Видалити",
    "Test": "Перевірити",
    "Save": "Зберегти",
    "Connect": "Підключитися",
    "Close": "Закрити",
    "Unsaved changes": "Незбережені зміни",
    "The connection has unsaved changes. Save them?": "У підключенні є незбережені зміни. Зберегти їх?",
    "Delete connection": "Видалення підключення",
    "Delete the connection “{name}”? Its saved password is removed too.": "Видалити підключення «{name}»? Збережений пароль також буде видалено.",
    "Connection works.": "Підключення працює.",
    "Saved.": "Збережено.",
    "No group": "Без групи",
    "The password was not saved: the password store is locked.": "Пароль не збережено: сховище паролів заблоковано.",
    "Testing the connection…": "Перевірка підключення…",
    "DNS lookup": "Пошук адреси (DNS)",
    "Port reachable": "Порт доступний",
    "Sign in": "Вхід",
    "Test query": "Тестовий запит",
    "Database file": "Файл бази даних",
    "Open file": "Відкриття файлу",
    "My database": "Моя база даних",
    "No colour": "Без кольору",
    "URL": "URL",
    "Host / Port": "Хост / порт",
    "File": "Файл",
    "Password": "Пароль",
    "Save the password in the {store}": "Зберегти пароль у сховищі ({store})",
    "password store": "сховище паролів",
    "Read-only": "Лише читання",
    "Production database": "Робоча (production) база",
    "Connection URL": "URL підключення",
    "Paste a URL and the fields update. The password is kept separately.": "Вставте URL, і поля оновляться. Пароль зберігається окремо.",
    "Open…": "Відкрити…",
    "New…": "Створити…",
    "Create the file if it does not exist": "Створити файл, якщо його немає",
    "Open database file": "Відкрити файл бази даних",
    "SQLite databases (*.db *.sqlite *.sqlite3 *.db3);;All files (*)": "Бази SQLite (*.db *.sqlite *.sqlite3 *.db3);;Усі файли (*)",
    "New database file": "Новий файл бази даних",
    "Host": "Хост",
    "Port": "Порт",
    "User": "Користувач",
    "Database": "База даних",
    "Extra parameters": "Додаткові параметри",
    "Give the connection a name.": "Вкажіть назву підключення.",
    "default ({port})": "типово ({port})",
    "Name": "Назва",
    "Colour": "Колір",
    "Group": "Група",
    "A saved password is used. Type to replace it.": "Використовується збережений пароль. Введіть новий, щоб замінити.",
    "Choose the database file.": "Виберіть файл бази даних.",
    "Red": "Червоний",
    "Orange": "Помаранчевий",
    "Yellow": "Жовтий",
    "Green": "Зелений",
    "Teal": "Бірюзовий",
    "Blue": "Синій",
    "Purple": "Фіолетовий",
    "Gray": "Сірий",
    "Manage connections…": "Керування підключеннями…",
    "Choose the database to work with": "Виберіть базу даних для роботи",
    "Connected": "Підключено",
    "Connecting…": "Підключення…",
    "Connection failed": "Не вдалося підключитися",
    "Not connected": "Немає підключення",
    "No saved connections": "Немає збережених підключень",
    "Select a connection": "Виберіть підключення",
    "Check the host name, your network connection and VPN.": "Перевірте назву хоста, мережеве підключення та VPN.",
    "The host is reachable but nothing accepts connections on this port. Check that the server is running and that the port is correct.": "Хост доступний, але на цьому порту ніхто не приймає підключення. Перевірте, чи запущено сервер і чи правильно вказано порт.",
    "The server did not answer in time. A firewall may be dropping the connection.": "Сервер не відповів вчасно. Можливо, підключення блокує брандмауер.",
    "Check the user name and the password.": "Перевірте ім'я користувача та пароль.",
    "The server is reachable, but it has no database with this name.": "Сервер доступний, але бази даних із такою назвою на ньому немає.",
    "Check the path of the database file.": "Перевірте шлях до файлу бази даних.",
    "Check the extra parameters of the connection.": "Перевірте додаткові параметри підключення.",
    "Set the missing environment variables and try again.": "Задайте відсутні змінні середовища та повторіть спробу.",
    "The saved password could not be read. Unlock the password store first.": "Не вдалося прочитати збережений пароль. Спершу розблокуйте сховище паролів.",
    "&File": "&Файл",
    "&Connections…": "&Підключення…",
    "&Quit": "&Вихід",
    "&View": "&Вигляд",
    "Language": "Мова",
    "Connections…": "Підключення…",
    "The database diagram will appear here.": "Тут з'явиться діаграма бази даних.",
    "The language changes the next time the application starts.": "Мова зміниться під час наступного запуску застосунку.",
    "Dark theme": "Темна тема",
    "Light theme": "Світла тема",
    "System default": "Як у системі",
    "No connection": "Немає підключення",
    "Connected to {name}": "Підключено до {name}",
    "Connecting to {name}…": "Підключення до {name}…",
    "Could not connect to {name}": "Не вдалося підключитися до {name}",
    "{name} is not connected": "{name}: немає підключення",
    "The password store stayed locked.": "Сховище паролів залишилося заблокованим.",
    "Password required": "Потрібен пароль",
    "Password for {name}:": "Пароль для {name}:",
    "A configuration file was damaged": "Файл конфігурації пошкоджено",
    "A configuration file could not be read. It was kept as:\n{path}\nValid entries were restored.": "Файл конфігурації не вдалося прочитати. Його збережено як:\n{path}\nКоректні записи відновлено.",
    "PRODUCTION": "PRODUCTION",
    "system keyring": "системне сховище паролів",
    "encrypted vault": "зашифроване сховище",
    "memory (until the app is closed)": "пам'ять (до закриття застосунку)",
    "No system keyring was found, so passwords are kept in an encrypted file protected by a master password.\n\nChoose a master password:": "Системне сховище паролів не знайдено, тому паролі зберігаються в зашифрованому файлі, захищеному майстер-паролем.\n\nПридумайте майстер-пароль:",
    "Master password for the saved passwords:": "Майстер-пароль для збережених паролів:",
    "Create master password": "Створення майстер-пароля",
    "Repeat the master password:": "Повторіть майстер-пароль:",
    "Unlock saved passwords": "Розблокування збережених паролів",
    "Wrong master password.": "Неправильний майстер-пароль.",
    "The passwords do not match.": "Паролі не збігаються.",
    "Wrong master password. Try again:": "Неправильний майстер-пароль. Спробуйте ще раз:",
    "Cancel": "Скасувати",
    "Retry": "Повторити",
    "Edit connection…": "Змінити підключення…",
    "Disconnect": "Відключитися",
    "No connection selected": "Підключення не вибрано",
    "Pick a database in the list on the right, or create a connection.": "Виберіть базу даних у списку праворуч або створіть підключення.",
    "Read and write": "Читання й запис",
    "Database system": "СУБД",
    "Address": "Адреса",
    "Mode": "Режим",
    "&Query": "&Запит",
    "&Run": "&Виконати",
    "Run &script": "Виконати &скрипт",
    "S&top": "З&упинити",
    "&Format": "&Форматувати",
    "&New tab": "&Нова вкладка",
    "&Close tab": "&Закрити вкладку",
    "Row limit": "Ліміт рядків",
    "Run": "Виконати",
    "Run script": "Виконати скрипт",
    "Stop": "Зупинити",
    "Format": "Форматувати",
    "New query tab (Ctrl+T)": "Нова вкладка запиту (Ctrl+T)",
    "Run the selection or the current statement (Ctrl+Enter)": "Виконати виділене або поточний оператор (Ctrl+Enter)",
    "Run every statement in order (F5)": "Виконати всі оператори по черзі (F5)",
    "Cancel the running query (Esc)": "Скасувати виконуваний запит (Esc)",
    "Format the SQL (Ctrl+Shift+F)": "Форматувати SQL (Ctrl+Shift+F)",
    "SQL dialect of this tab": "Діалект SQL цієї вкладки",
    "Query {n}": "Запит {n}",
    "Rename tab": "Перейменування вкладки",
    "Tab name:": "Назва вкладки:",
    "Cancelling…": "Скасування…",
    "The connection is not ready.": "Підключення не готове.",
    "There is nothing to run.": "Нічого виконувати.",
    "drops {target}": "видаляє {target}",
    "empties {target}": "повністю очищає {target}",
    "deletes every row of {target}": "видаляє всі рядки в {target}",
    "changes every row of {target}": "змінює всі рядки в {target}",
    "an object": "об'єкт",
    "it changes data on the PRODUCTION connection “{name}”": "змінює дані в PRODUCTION-підключенні «{name}»",
    "Run this?": "Виконати?",
    "This script:": "Цей скрипт:",
    "Run it anyway?": "Усе одно виконати?",
    "Failed after {time}": "Помилка через {time}",
    "Cancelled after {time}": "Скасовано через {time}",
    "Done in {time}": "Виконано за {time}",
    "Running… {time}": "Виконується… {time}",
    "line": "рядок",
    "column": "стовпець",
    "Formatted.": "Відформатовано.",
    "Filter rows…": "Фільтр рядків…",
    "Your query returned no data": "Запит не повернув жодних даних",
    "{count} rows": "Рядків: {count}",
    "{shown} of {total} rows": "Рядків: {shown} із {total}",
    "cut off at {limit} rows": "обмежено {limit} рядками",
    "Run a query to see results here.": "Виконайте запит, щоб побачити тут результати.",
    "Result {n}": "Результат {n}",
    "Query OK": "Запит виконано",
    "{count} rows affected": "Зачеплено рядків: {count}",
    "OK {n}": "Готово {n}",
    "Query failed": "Помилка запиту",
    "Error {n}": "Помилка {n}",
    "Cancelled": "Скасовано",
    "The statement was stopped.": "Виконання оператора зупинено.",
    "Cancelled {n}": "Скасовано {n}",
    "Skipped": "Пропущено",
    "An earlier statement failed or was cancelled.": "Попередній оператор завершився помилкою або був скасований.",
    "Skipped {n}": "Пропущено {n}",
    "A saved passphrase is used. Type to replace it.": "Використовується збережена парольна фраза. Введіть нову, щоб замінити.",
    "A saved secret is used. Type to replace it.": "Використовується збережений секрет. Введіть новий, щоб замінити.",
    "All files (*)": "Усі файли (*)",
    "Always encrypted, but the server's identity is not checked.": "Завжди шифрується, але справжність сервера не перевіряється.",
    "Browse…": "Огляд…",
    "CA certificate": "Сертифікат CA",
    "Check the SSH host name and port, your network connection and VPN.": "Перевірте ім'я хоста й порт SSH, мережеве підключення та VPN.",
    "Check the SSH private key file and its passphrase.": "Перевірте файл закритого SSH-ключа та його парольну фразу.",
    "Choose a file": "Виберіть файл",
    "Client certificate": "Клієнтський сертифікат",
    "Client key": "Клієнтський ключ",
    "Connect through an SSH tunnel": "Підключатися через SSH-тунель",
    "Define the service in ~/.pg_service.conf or choose another one.": "Опишіть сервіс у ~/.pg_service.conf або виберіть інший.",
    "Driver default": "За замовчуванням (драйвер)",
    "Encrypted; the certificate must be signed by the CA below (or a system CA).": "Шифрується; сертифікат має бути підписаний вказаним нижче CA (або системним).",
    "Encryption": "Шифрування",
    "Enter the SSH server host name.": "Вкажіть ім'я хоста SSH-сервера.",
    "Enter the host name (or a service).": "Вкажіть ім'я хоста (або сервіс).",
    "Enter the jump host name.": "Вкажіть ім'я проміжного вузла.",
    "Fix the certificate or key file named above in the SSL / TLS tab.": "Виправте файл сертифіката або ключа, указаний вище, на вкладці SSL / TLS.",
    "Jump host": "Проміжний вузол",
    "Jump host password for {name}:": "Пароль проміжного вузла для {name}:",
    "Key passphrase": "Парольна фраза ключа",
    "Key passphrase (if the key has one)": "Парольна фраза ключа (якщо вона є)",
    "Like verify-ca, and the certificate must be issued for the host name.": "Як verify-ca, і сертифікат має бути виданий для цього імені хоста.",
    "No encryption at all.": "Без шифрування.",
    "PEM files (*.pem *.crt *.cer *.key);;All files (*)": "Файли PEM (*.pem *.crt *.cer *.key);;Усі файли (*)",
    "Passphrase of the SSH key for {name}:": "Парольна фраза SSH-ключа для {name}:",
    "Passphrase of the TLS client key for {name}:": "Парольна фраза клієнтського TLS-ключа для {name}:",
    "Passphrase of the jump host key for {name}:": "Парольна фраза ключа проміжного вузла для {name}:",
    "Password source": "Джерело пароля",
    "Plain first; TLS only if the server insists (PostgreSQL).": "Спершу без шифрування; TLS, лише якщо цього вимагає сервер (PostgreSQL).",
    "Private key": "Закритий ключ",
    "Private key file": "Файл закритого ключа",
    "Reach the SSH server through a jump host (bastion)": "Підключатися до SSH-сервера через проміжний вузол (бастіон)",
    "SSH jump host": "SSH: проміжний вузол",
    "SSH login": "SSH: вхід",
    "SSH password for {name}:": "SSH-пароль для {name}:",
    "SSH passwords and key passphrases are kept the same way.": "SSH-паролі та парольні фрази ключів зберігаються так само.",
    "SSH server": "SSH-сервер",
    "SSH tunnel": "SSH-тунель",
    "SSL / TLS": "SSL / TLS",
    "Secret for {name}:": "Секрет для {name}:",
    "Service": "Сервіс",
    "Service file": "Файл сервісів",
    "Settings": "Налаштування",
    "Sign in with": "Спосіб входу",
    "TLS files": "Файли TLS",
    "TLS negotiation failed. Check the mode and the certificates in the SSL / TLS tab.": "Не вдалося узгодити TLS. Перевірте режим і сертифікати на вкладці SSL / TLS.",
    "TLS when the server offers it, otherwise plain.": "TLS, якщо сервер його пропонує, інакше без шифрування.",
    "The SSH login worked, but the SSH server cannot reach the database host and port. Check them from the SSH server's point of view.": "Вхід через SSH виконано, але SSH-сервер не може дістатися до хоста й порту бази даних. Перевірте їх з погляду SSH-сервера.",
    "The SSH server refused the login. Check the user, the password or the key.": "SSH-сервер відхилив вхід. Перевірте користувача, пароль або ключ.",
    "The SSH server's key is not the one you trusted. If nobody reinstalled the server, do not connect: somebody may be intercepting the connection.": "Ключ SSH-сервера не збігається з тим, якому ви довіряли. Якщо ніхто не перевстановлював сервер, не підключайтеся: підключення можуть перехоплювати.",
    "The driver decides: PostgreSQL tries TLS first, MySQL uses it when offered.": "Вирішує драйвер: PostgreSQL спершу пробує TLS, MySQL використовує його, якщо сервер пропонує.",
    "The identity of {host}:{port} is not known yet.\n\n{key_type} key fingerprint:\n{fingerprint}\n\nCompare it with the one your administrator gave you. Trust this server?": "Ідентичність {host}:{port} поки невідома.\n\nВідбиток ключа {key_type}:\n{fingerprint}\n\nПорівняйте його з тим, який надав адміністратор. Довіряти цьому серверу?",
    "This SSH server has not been seen before. Compare its fingerprint with the administrator's, then trust it.": "Цей SSH-сервер раніше не зустрічався. Порівняйте його відбиток із відбитком від адміністратора й лише тоді довіряйте.",
    "Trust this SSH server?": "Довіряти цьому SSH-серверу?",
    "Trust this server…": "Довіряти цьому серверу…",
    "Type the SSH password or key passphrase (SSH tunnel tab) and try again.": "Введіть SSH-пароль або парольну фразу ключа (вкладка «SSH-тунель») і повторіть спробу.",
    "optional — a service from pg_service.conf": "необов'язково — сервіс із pg_service.conf",
    "ssh-agent": "ssh-agent",
    "{file} has a password for this connection (line {line}); it is used when none is saved.": "У {file} є пароль для цього підключення (рядок {line}); він використовується, якщо збереженого немає.",
    "{file} has no line for this connection.": "У {file} немає рядка для цього підключення.",
    "&History…": "&Історія…",
    "&Save query…": "&Зберегти запит…",
    "Sa&ved queries…": "Збере&жені запити…",
    "Changed": "Змінено",
    "Clear history": "Очищення історії",
    "Clear history…": "Очистити історію…",
    "Delete query": "Видалення запиту",
    "Delete the saved query “{name}”?": "Видалити збережений запит «{name}»?",
    "Delete the whole history of this connection? Saved queries are kept.": "Видалити всю історію цього підключення? Збережені запити залишаться.",
    "Dialect": "Діалект",
    "Folder (empty: none):": "Папка (порожньо — без папки):",
    "Folder (optional)": "Папка (необов'язково)",
    "History": "Історія",
    "History and saved queries — {name}": "Історія та збережені запити — {name}",
    "Insert at the cursor": "Вставити в позицію курсора",
    "Monthly revenue": "Дохід за місяць",
    "Move to a folder": "Переміщення до папки",
    "Move to a folder…": "Перемістити до папки…",
    "Name:": "Назва:",
    "No folder": "Без папки",
    "Only failures": "Лише помилки",
    "Only for this connection": "Лише для цього підключення",
    "Open in a new tab": "Відкрити в новій вкладці",
    "Rename query": "Перейменування запиту",
    "Rename…": "Перейменувати…",
    "Result": "Результат",
    "Save as a query…": "Зберегти як запит…",
    "Save query": "Збереження запиту",
    "Saved queries": "Збережені запити",
    "Saved the query “{name}”.": "Запит «{name}» збережено.",
    "Search saved queries…": "Шукати в збережених запитах…",
    "Search the history…": "Шукати в історії…",
    "Statement": "Оператор",
    "There is nothing to save.": "Нічого зберігати.",
    "Time": "Час",
    "When": "Коли",
    "cancelled": "скасовано",
    "done": "виконано",
    "failed": "помилка",
    "just now": "щойно",
    "today {time}": "сьогодні {time}",
    "yesterday {time}": "учора {time}",
    "{n} min ago": "{n} хв тому",
    "&Export diagram…": "&Експорт діаграми…",
    "Cannot write {path}": "Не вдалося записати {path}",
    "DBML schema (text)": "Схема DBML (текст)",
    "Diagram saved to {path}": "Діаграму збережено: {path}",
    "Export the diagram": "Експорт діаграми",
    "Export the diagram as an image, PDF or text…": "Експорт діаграми: зображення, PDF або текст…",
    "Mermaid diagram (text)": "Діаграма Mermaid (текст)",
    "PDF document": "Документ PDF",
    "PNG image": "Зображення PNG",
    "SVG drawing": "Малюнок SVG",
    "There is no diagram to export yet.": "Діаграми для експорту поки немає.",
    "There is nothing to export.": "Експортувати нічого.",
    "Unknown file type: use .png, .svg, .pdf, .mmd or .dbml.": "Невідомий тип файлу: використовуйте .png, .svg, .pdf, .mmd або .dbml.",
    "The folder {path} does not exist.": "Папки {path} не існує.",
    "AWS RDS / Aurora (IAM)": "AWS RDS / Aurora (IAM)",
    "AWS profile": "Профіль AWS",
    "AWS region": "Регіон AWS",
    "Azure Database (Microsoft Entra ID)": "Azure Database (Microsoft Entra ID)",
    "Check the settings in the Cloud tab.": "Перевірте налаштування на вкладці «Хмара».",
    "Cloud": "Хмара",
    "Cloud token": "Хмарний токен",
    "Cluster name (Serverless)": "Назва кластера (Serverless)",
    "CockroachDB Cloud": "CockroachDB Cloud",
    "Endpoint host": "Хост endpoint",
    "Google Cloud SQL (IAM)": "Google Cloud SQL (IAM)",
    "Hosted service": "Хмарний сервіс",
    "Install the provider's package: pip install 'easydbms[{extra}]'": "Встановіть пакет провайдера: pip install 'easydbms[{extra}]'",
    "Managed identity client ID": "Client ID керованої ідентичності",
    "MySQL. The host, user and password come from the branch's Connect dialog. TLS with a verified certificate is required.": "MySQL. Хост, користувач і пароль беруться з вікна Connect вашої гілки. Потрібен TLS із перевіркою сертифіката.",
    "Neon": "Neon",
    "No password: a 15-minute token is created from your AWS credentials every time the connection opens. The database user must be enabled for IAM authentication.": "Без пароля: під час кожного підключення за вашими обліковими даними AWS створюється токен на 15 хвилин. Для користувача БД має бути ввімкнено автентифікацію IAM.",
    "No password: an Entra access token is requested every time the connection opens. The user is the Entra principal (for PostgreSQL usually name@tenant.onmicrosoft.com).": "Без пароля: під час кожного підключення запитується токен доступу Entra. Користувач — суб'єкт Entra (для PostgreSQL зазвичай name@tenant.onmicrosoft.com).",
    "No password: your Google account's access token is the password. The user is the IAM principal (a PostgreSQL service account without .gserviceaccount.com, a MySQL user without the domain). Use the instance IP or a running Cloud SQL Auth Proxy.": "Без пароля: паролем слугує токен доступу вашого облікового запису Google. Користувач — суб'єкт IAM (для PostgreSQL службовий обліковий запис без .gserviceaccount.com, для MySQL — користувач без домену). Підключайтеся до IP екземпляра або до запущеного Cloud SQL Auth Proxy.",
    "None — a regular server": "Немає — звичайний сервер",
    "Pick AWS, Google Cloud, Azure, Supabase, Neon, PlanetScale or CockroachDB to get its settings filled in.": "Виберіть AWS, Google Cloud, Azure, Supabase, Neon, PlanetScale або CockroachDB, і налаштування заповняться автоматично.",
    "PlanetScale": "PlanetScale",
    "PostgreSQL protocol, port 26257. For a Serverless cluster the cluster name goes in front of the database name. Download the cluster's CA certificate and choose it in the SSL / TLS tab for full verification.": "Протокол PostgreSQL, порт 26257. Для кластера Serverless назва кластера ставиться перед назвою бази даних. Завантажте CA-сертифікат кластера й виберіть його на вкладці SSL / TLS для повної перевірки.",
    "PostgreSQL. Direct connection to db.<project-ref>.supabase.co with the password set in Project Settings → Database. TLS is required.": "PostgreSQL. Пряме підключення до db.<project-ref>.supabase.co з паролем, заданим у Project Settings → Database. Потрібен TLS.",
    "PostgreSQL. Paste the host from the Neon console's connection details (ep-….neon.tech, or the -pooler one). TLS is required.": "PostgreSQL. Вставте хост із параметрів підключення в консолі Neon (ep-….neon.tech або з -pooler). Потрібен TLS.",
    "Project reference": "Ідентифікатор проєкту",
    "Service account key file": "Файл ключа службового облікового запису",
    "Sign in to the cloud account (CLI or environment variables) and try again.": "Увійдіть у хмарний обліковий запис (через CLI або змінні середовища) і повторіть спробу.",
    "Supabase": "Supabase",
    "eu-west-1 (read from the host name if empty)": "eu-west-1 (якщо порожньо — береться з імені хоста)",
    "only for a user-assigned identity": "лише для ідентичності, призначеної користувачем",
    "optional (JSON)": "необов'язково (JSON)",
    "System theme": "Системна тема",
}
