"""Russian translations, keyed by the English source string."""

RU: dict[str, str] = {
    # connection dialog
    "Connections": "Подключения",
    "Saved connections": "Сохранённые подключения",
    "+ New": "+ Новое",
    "Duplicate": "Дублировать",
    "Delete": "Удалить",
    "Test": "Проверить",
    "Save": "Сохранить",
    "Connect": "Подключиться",
    "Close": "Закрыть",
    "Unsaved changes": "Несохранённые изменения",
    "The connection has unsaved changes. Save them?": "В подключении есть несохранённые изменения. Сохранить их?",
    "Delete connection": "Удаление подключения",
    "Delete the connection “{name}”? Its saved password is removed too.": "Удалить подключение «{name}»? Сохранённый пароль тоже будет удалён.",
    "Connection works.": "Подключение работает.",
    "Saved.": "Сохранено.",
    "No group": "Без группы",
    "The password was not saved: the password store is locked.": "Пароль не сохранён: хранилище паролей заблокировано.",
    "Testing the connection…": "Проверяем подключение…",
    # test steps
    "DNS lookup": "Поиск адреса (DNS)",
    "Port reachable": "Порт доступен",
    "Sign in": "Вход",
    "Test query": "Тестовый запрос",
    "Database file": "Файл базы данных",
    "Open file": "Открытие файла",
    # form
    "My database": "Моя база данных",
    "No colour": "Без цвета",
    "URL": "URL",
    "Host / Port": "Хост / порт",
    "File": "Файл",
    "Password": "Пароль",
    "Save the password in the {store}": "Сохранить пароль в хранилище ({store})",
    "password store": "хранилище паролей",
    "Read-only": "Только чтение",
    "Production database": "Рабочая (production) база",
    "Connection URL": "URL подключения",
    "Paste a URL and the fields update. The password is kept separately.": "Вставьте URL, и поля обновятся. Пароль хранится отдельно.",
    "Open…": "Открыть…",
    "New…": "Создать…",
    "Create the file if it does not exist": "Создать файл, если его нет",
    "Open database file": "Открыть файл базы данных",
    "SQLite databases (*.db *.sqlite *.sqlite3 *.db3);;All files (*)": "Базы SQLite (*.db *.sqlite *.sqlite3 *.db3);;Все файлы (*)",
    "New database file": "Новый файл базы данных",
    "Host": "Хост",
    "Port": "Порт",
    "User": "Пользователь",
    "Database": "База данных",
    "Extra parameters": "Дополнительные параметры",
    "Give the connection a name.": "Укажите название подключения.",
    "default ({port})": "по умолчанию ({port})",
    "Name": "Название",
    "Colour": "Цвет",
    "Group": "Группа",
    "A saved password is used. Type to replace it.": "Используется сохранённый пароль. Введите новый, чтобы заменить.",
    "Choose the database file.": "Выберите файл базы данных.",
    "Enter the host name.": "Укажите имя хоста.",
    "Red": "Красный",
    "Orange": "Оранжевый",
    "Yellow": "Жёлтый",
    "Green": "Зелёный",
    "Teal": "Бирюзовый",
    "Blue": "Синий",
    "Purple": "Фиолетовый",
    "Gray": "Серый",
    # db switcher
    "Manage connections…": "Управление подключениями…",
    "Choose the database to work with": "Выберите базу данных для работы",
    "Connected": "Подключено",
    "Connecting…": "Подключение…",
    "Connection failed": "Не удалось подключиться",
    "Not connected": "Нет подключения",
    "No saved connections": "Нет сохранённых подключений",
    "Select a connection": "Выберите подключение",
    # failure hints
    "Check the host name, your network connection and VPN.": "Проверьте имя хоста, сетевое подключение и VPN.",
    "The host is reachable but nothing accepts connections on this port. Check that the server is running and that the port is correct.": "Хост доступен, но на этом порту никто не принимает подключения. Проверьте, что сервер запущен и порт указан верно.",
    "The server did not answer in time. A firewall may be dropping the connection.": "Сервер не ответил вовремя. Возможно, подключение блокирует файрвол.",
    "Check the user name and the password.": "Проверьте имя пользователя и пароль.",
    "The server is reachable, but it has no database with this name.": "Сервер доступен, но базы данных с таким именем на нём нет.",
    "TLS negotiation failed. Check the sslmode or certificate parameters.": "Не удалось установить TLS-соединение. Проверьте параметры sslmode или сертификатов.",
    "Check the path of the database file.": "Проверьте путь к файлу базы данных.",
    "Check the extra parameters of the connection.": "Проверьте дополнительные параметры подключения.",
    "Set the missing environment variables and try again.": "Задайте недостающие переменные окружения и повторите попытку.",
    "The saved password could not be read. Unlock the password store first.": "Не удалось прочитать сохранённый пароль. Сначала разблокируйте хранилище паролей.",
    # main window
    "&File": "&Файл",
    "&Connections…": "&Подключения…",
    "&Quit": "&Выход",
    "&View": "&Вид",
    "Language": "Язык",
    "Connections…": "Подключения…",
    "The database diagram will appear here.": "Здесь появится диаграмма базы данных.",
    "The language changes the next time the application starts.": "Язык изменится при следующем запуске приложения.",
    "Dark theme": "Тёмная тема",
    "Light theme": "Светлая тема",
    "System default": "Как в системе",
    "No connection": "Нет подключения",
    "Connected to {name}": "Подключено: {name}",
    "Connecting to {name}…": "Подключение к {name}…",
    "Could not connect to {name}": "Не удалось подключиться к {name}",
    "{name} is not connected": "{name}: нет подключения",
    "The password store stayed locked.": "Хранилище паролей осталось заблокированным.",
    "Password required": "Нужен пароль",
    "Password for {name}:": "Пароль для {name}:",
    "A configuration file was damaged": "Файл конфигурации повреждён",
    "A configuration file could not be read. It was kept as:\n{path}\nValid entries were restored.": "Файл конфигурации не удалось прочитать. Он сохранён как:\n{path}\nКорректные записи восстановлены.",
    "PRODUCTION": "PRODUCTION",
    "system keyring": "системное хранилище",
    "encrypted vault": "зашифрованное хранилище",
    "memory (until the app is closed)": "память, до закрытия приложения",
    # master password
    "No system keyring was found, so passwords are kept in an encrypted file protected by a master password.\n\nChoose a master password:": "Системное хранилище паролей не найдено, поэтому пароли хранятся в зашифрованном файле, защищённом мастер-паролем.\n\nПридумайте мастер-пароль:",
    "Master password for the saved passwords:": "Мастер-пароль для сохранённых паролей:",
    "Create master password": "Создание мастер-пароля",
    "Repeat the master password:": "Повторите мастер-пароль:",
    "Unlock saved passwords": "Разблокировка сохранённых паролей",
    "Wrong master password.": "Неверный мастер-пароль.",
    "The passwords do not match.": "Пароли не совпадают.",
    "Wrong master password. Try again:": "Неверный мастер-пароль. Попробуйте ещё раз:",
    # session panel
    "Cancel": "Отмена",
    "Retry": "Повторить",
    "Edit connection…": "Изменить подключение…",
    "Disconnect": "Отключиться",
    "No connection selected": "Подключение не выбрано",
    "Pick a database in the list on the right, or create a connection.": "Выберите базу в списке справа или создайте подключение.",
    "Read and write": "Чтение и запись",
    "Database system": "СУБД",
    "Address": "Адрес",
    "Mode": "Режим",
}
