"""Saved connections: models, URL handling, secrets and persistence."""

from .complete import Completed, complete
from .env import UnresolvedVariableError, expand, has_placeholders, resolve_config
from .models import (
    ConnectionColor,
    ConnectionConfig,
    FileConnection,
    ProviderConfig,
    ProviderKind,
    ServerConnection,
    SshAuth,
    SshConfig,
    SshHop,
    SslConfig,
    SslMode,
    parse_config,
    replace,
)
from .pgfiles import (
    PgPass,
    PgPassMatch,
    Service,
    ServiceNotFoundError,
    find_service,
    load_pgpass,
    load_services,
    parse_pgpass,
    parse_service_file,
    pgpass_path,
    service_file_paths,
)
from .secrets import (
    ALL_FIELDS,
    JUMP_PASSPHRASE,
    JUMP_PASSWORD,
    PASSWORD,
    SSH_PASSPHRASE,
    SSH_PASSWORD,
    SSL_KEY_PASSWORD,
    KeyringSecretStore,
    MemorySecretStore,
    SecretStore,
    SecretStoreError,
    VaultLockedError,
    VaultSecretStore,
    WrongPasswordError,
    choose_secret_store,
)
from .store import ConnectionNotFoundError, ConnectionStore
from .url_parser import (
    MEMORY_DATABASE,
    ConnectionUrlError,
    ParsedUrl,
    build_connection_url,
    parse_connection_url,
)

__all__ = [
    "ALL_FIELDS",
    "JUMP_PASSPHRASE",
    "JUMP_PASSWORD",
    "MEMORY_DATABASE",
    "PASSWORD",
    "SSH_PASSPHRASE",
    "SSH_PASSWORD",
    "SSL_KEY_PASSWORD",
    "Completed",
    "ConnectionColor",
    "ConnectionConfig",
    "ConnectionNotFoundError",
    "ConnectionStore",
    "ConnectionUrlError",
    "FileConnection",
    "KeyringSecretStore",
    "MemorySecretStore",
    "ParsedUrl",
    "PgPass",
    "PgPassMatch",
    "ProviderConfig",
    "ProviderKind",
    "SecretStore",
    "SecretStoreError",
    "ServerConnection",
    "Service",
    "ServiceNotFoundError",
    "SshAuth",
    "SshConfig",
    "SshHop",
    "SslConfig",
    "SslMode",
    "UnresolvedVariableError",
    "VaultLockedError",
    "VaultSecretStore",
    "WrongPasswordError",
    "build_connection_url",
    "choose_secret_store",
    "complete",
    "expand",
    "find_service",
    "has_placeholders",
    "load_pgpass",
    "load_services",
    "parse_config",
    "parse_connection_url",
    "parse_pgpass",
    "parse_service_file",
    "pgpass_path",
    "replace",
    "resolve_config",
    "service_file_paths",
]
